name: Build Images
on:
  push:
    branches:
      - "develop"
    paths:
      - "boards/**"
      - "configs/**"
      - ".github/workflows/**"
      - "actions/**"

  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - "boards/**"
      - "configs/**"
      - ".github/workflows/**"
      - "actions/**"

  workflow_dispatch:

concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  setup:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      configfiles: ${{ steps.set-matrix.outputs.configfiles }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Matrix
        id: set-matrix
        run: |
          JSON=$(find ${{ github.workspace }}/configs -type f -name "smartpi1-*.conf" -printf '%f\n' | sed 's#smartpi1-##;s#.conf##' | jq -R -s -c 'split("\n")[:-1]')
          echo "configfiles=${JSON}" >> $GITHUB_OUTPUT
          echo "::group::Build Matrix"
          echo "${JSON}"
          echo "::endgroup::"

  build:
    name: Build Images
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      fail-fast: true
      matrix:
        configfile: ${{ fromJson(needs.setup.outputs.configfiles) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: build-configs
          fetch-depth: 0

      - name: Build
        uses: ./build-configs/actions/build-image
        with:
          configfile: ${{ matrix.configfile }}

      - name: Rename Files
        run: |
          cd ${{ github.workspace }}/build/output/images/
          mv *.img armbian-${{ matrix.configfile }}.img
          mv *.txt armbian-${{ matrix.configfile }}.txt

      - name: Compressing Image
        run: |
          cd ${{ github.workspace }}/build/output/images/
          xz -efkvz armbian-${{ matrix.configfile }}.img || true

      - name: Calculating checksums
        run: |
          cd ${{ github.workspace }}/build/output/images/
          sha256sum armbian-${{ matrix.configfile }}.img > armbian-${{ matrix.configfile }}.img.sha256
          sha256sum armbian-${{ matrix.configfile }}.img.xz > armbian-${{ matrix.configfile }}.img.xz.sha256

      - name: DEBUG
        run: |
          ls -l ${{ github.workspace }}/build/output/images/
