name: Build Images
on:
  push:
    branches:
      - "develop"
    paths:
      - "boards/**"
      - "configs/**"
      - ".github/workflows/**"

  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - "boards/**"
      - "configs/**"
      - ".github/workflows/**"

  workflow_dispatch:

concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  setup:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      configfiles: ${{ steps.set-matrix.outputs.configfiles }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Matrix
        id: set-matrix
        run: |
          JSON=$(find ${{ github.workspace }}/configs -type f -name "smartpi1-*.conf" -printf '%f\n' | sed 's#board-##;s#.conf##' | jq -R -s -c 'split("\n")[:-1]')
          echo "configfiles=${JSON}" >> $GITHUB_OUTPUT
          echo "::group::Build Matrix"
          echo "${JSON}"
          echo "::endgroup::"

  build:
    name: Build Images
    runs-on: ubuntu-latest
